from enum import IntEnum, IntFlag

class ApplyLocation(IntEnum):
    WORKDIR = ...
    INDEX = ...
    BOTH = ...

class AttrCheck(IntFlag):
    FILE_THEN_INDEX = ...
    INDEX_THEN_FILE = ...
    INDEX_ONLY = ...
    NO_SYSTEM = ...
    INCLUDE_HEAD = ...
    INCLUDE_COMMIT = ...

class BlameFlag(IntFlag):
    NORMAL = ...
    TRACK_COPIES_SAME_FILE = ...
    TRACK_COPIES_SAME_COMMIT_MOVES = ...
    TRACK_COPIES_SAME_COMMIT_COPIES = ...
    TRACK_COPIES_ANY_COMMIT_COPIES = ...
    FIRST_PARENT = ...
    USE_MAILMAP = ...
    IGNORE_WHITESPACE = ...

class BlobFilter(IntFlag):
    CHECK_FOR_BINARY = ...
    NO_SYSTEM_ATTRIBUTES = ...
    ATTRIBUTES_FROM_HEAD = ...
    ATTRIBUTES_FROM_COMMIT = ...

class BranchType(IntFlag):
    LOCAL = ...
    REMOTE = ...
    ALL = ...

class CheckoutNotify(IntFlag):
    NONE = ...
    CONFLICT = ...
    DIRTY = ...
    UPDATED = ...
    UNTRACKED = ...
    IGNORED = ...
    ALL = ...

class CheckoutStrategy(IntFlag):
    NONE = ...
    SAFE = ...
    FORCE = ...
    RECREATE_MISSING = ...
    ALLOW_CONFLICTS = ...
    REMOVE_UNTRACKED = ...
    REMOVE_IGNORED = ...
    UPDATE_ONLY = ...
    DONT_UPDATE_INDEX = ...
    NO_REFRESH = ...
    SKIP_UNMERGED = ...
    USE_OURS = ...
    USE_THEIRS = ...
    DISABLE_PATHSPEC_MATCH = ...
    SKIP_LOCKED_DIRECTORIES = ...
    DONT_OVERWRITE_IGNORED = ...
    CONFLICT_STYLE_MERGE = ...
    CONFLICT_STYLE_DIFF3 = ...
    DONT_REMOVE_EXISTING = ...
    DONT_WRITE_INDEX = ...
    DRY_RUN = ...
    CONFLICT_STYLE_ZDIFF3 = ...

class ConfigLevel(IntEnum):
    PROGRAMDATA = ...
    SYSTEM = ...
    XDG = ...
    GLOBAL = ...
    LOCAL = ...
    APP = ...
    HIGHEST_LEVEL = ...

class CredentialType(IntFlag):
    USERPASS_PLAINTEXT = ...
    SSH_KEY = ...
    SSH_CUSTOM = ...
    DEFAULT = ...
    SSH_INTERACTIVE = ...
    USERNAME = ...
    SSH_MEMORY = ...

class DeltaStatus(IntEnum):
    UNMODIFIED = ...
    ADDED = ...
    DELETED = ...
    MODIFIED = ...
    RENAMED = ...
    COPIED = ...
    IGNORED = ...
    UNTRACKED = ...
    TYPECHANGE = ...
    UNREADABLE = ...
    CONFLICTED = ...

class DescribeStrategy(IntEnum):
    DEFAULT = ...
    TAGS = ...
    ALL = ...

class DiffFind(IntFlag):
    FIND_BY_CONFIG = ...
    FIND_RENAMES = ...
    FIND_RENAMES_FROM_REWRITES = ...
    FIND_COPIES = ...
    FIND_COPIES_FROM_UNMODIFIED = ...
    FIND_REWRITES = ...
    BREAK_REWRITES = ...
    FIND_AND_BREAK_REWRITES = ...
    FIND_FOR_UNTRACKED = ...
    FIND_ALL = ...
    FIND_IGNORE_LEADING_WHITESPACE = ...
    FIND_IGNORE_WHITESPACE = ...
    FIND_DONT_IGNORE_WHITESPACE = ...
    FIND_EXACT_MATCH_ONLY = ...
    BREAK_REWRITES_FOR_RENAMES_ONLY = ...
    FIND_REMOVE_UNMODIFIED = ...

class DiffFlag(IntFlag):
    BINARY = ...
    NOT_BINARY = ...
    VALID_ID = ...
    EXISTS = ...
    VALID_SIZE = ...

class DiffOption(IntFlag):
    NORMAL = ...
    REVERSE = ...
    INCLUDE_IGNORED = ...
    RECURSE_IGNORED_DIRS = ...
    INCLUDE_UNTRACKED = ...
    RECURSE_UNTRACKED_DIRS = ...
    INCLUDE_UNMODIFIED = ...
    INCLUDE_TYPECHANGE = ...
    INCLUDE_TYPECHANGE_TREES = ...
    IGNORE_FILEMODE = ...
    IGNORE_SUBMODULES = ...
    IGNORE_CASE = ...
    INCLUDE_CASECHANGE = ...
    DISABLE_PATHSPEC_MATCH = ...
    SKIP_BINARY_CHECK = ...
    ENABLE_FAST_UNTRACKED_DIRS = ...
    UPDATE_INDEX = ...
    INCLUDE_UNREADABLE = ...
    INCLUDE_UNREADABLE_AS_UNTRACKED = ...
    INDENT_HEURISTIC = ...
    IGNORE_BLANK_LINES = ...
    FORCE_TEXT = ...
    FORCE_BINARY = ...
    IGNORE_WHITESPACE = ...
    IGNORE_WHITESPACE_CHANGE = ...
    IGNORE_WHITESPACE_EOL = ...
    SHOW_UNTRACKED_CONTENT = ...
    SHOW_UNMODIFIED = ...
    PATIENCE = ...
    MINIMAL = ...
    SHOW_BINARY = ...

class DiffStatsFormat(IntFlag):
    NONE = ...
    FULL = ...
    SHORT = ...
    NUMBER = ...
    INCLUDE_SUMMARY = ...

class Feature(IntFlag):
    THREADS = ...
    HTTPS = ...
    SSH = ...
    NSEC = ...

class FetchPrune(IntEnum):
    UNSPECIFIED = ...
    PRUNE = ...
    NO_PRUNE = ...

class FileMode(IntFlag):
    UNREADABLE = ...
    TREE = ...
    BLOB = ...
    BLOB_EXECUTABLE = ...
    LINK = ...
    COMMIT = ...

class FileStatus(IntFlag):
    CURRENT = ...
    INDEX_NEW = ...
    INDEX_MODIFIED = ...
    INDEX_DELETED = ...
    INDEX_RENAMED = ...
    INDEX_TYPECHANGE = ...
    WT_NEW = ...
    WT_MODIFIED = ...
    WT_DELETED = ...
    WT_TYPECHANGE = ...
    WT_RENAMED = ...
    WT_UNREADABLE = ...
    IGNORED = ...
    CONFLICTED = ...

class FilterFlag(IntFlag):
    DEFAULT = ...
    ALLOW_UNSAFE = ...
    NO_SYSTEM_ATTRIBUTES = ...
    ATTRIBUTES_FROM_HEAD = ...
    ATTRIBUTES_FROM_COMMIT = ...

class FilterMode(IntEnum):
    TO_WORKTREE = ...
    SMUDGE = ...
    TO_ODB = ...
    CLEAN = ...

class MergeAnalysis(IntFlag):
    NONE = ...
    NORMAL = ...
    UP_TO_DATE = ...
    FASTFORWARD = ...
    UNBORN = ...

class MergeFavor(IntEnum):
    NORMAL = ...
    OURS = ...
    THEIRS = ...
    UNION = ...

class MergeFileFlag(IntFlag):
    DEFAULT = ...
    STYLE_MERGE = ...
    STYLE_DIFF3 = ...
    SIMPLIFY_ALNUM = ...
    IGNORE_WHITESPACE = ...
    IGNORE_WHITESPACE_CHANGE = ...
    IGNORE_WHITESPACE_EOL = ...
    DIFF_PATIENCE = ...
    DIFF_MINIMAL = ...
    STYLE_ZDIFF3 = ...
    ACCEPT_CONFLICTS = ...

class MergeFlag(IntFlag):
    FIND_RENAMES = ...
    FAIL_ON_CONFLICT = ...
    SKIP_REUC = ...
    NO_RECURSIVE = ...
    VIRTUAL_BASE = ...

class MergePreference(IntFlag):
    NONE = ...
    NO_FASTFORWARD = ...
    FASTFORWARD_ONLY = ...

class ObjectType(IntEnum):
    ANY = ...
    INVALID = ...
    COMMIT = ...
    TREE = ...
    BLOB = ...
    TAG = ...
    OFS_DELTA = ...
    REF_DELTA = ...

class Option(IntEnum):
    GET_MWINDOW_SIZE = ...
    SET_MWINDOW_SIZE = ...
    GET_MWINDOW_MAPPED_LIMIT = ...
    SET_MWINDOW_MAPPED_LIMIT = ...
    GET_MWINDOW_FILE_LIMIT = ...
    SET_MWINDOW_FILE_LIMIT = ...
    GET_SEARCH_PATH = ...
    SET_SEARCH_PATH = ...
    SET_CACHE_OBJECT_LIMIT = ...
    SET_CACHE_MAX_SIZE = ...
    ENABLE_CACHING = ...
    GET_CACHED_MEMORY = ...
    GET_TEMPLATE_PATH = ...
    SET_TEMPLATE_PATH = ...
    SET_SSL_CERT_LOCATIONS = ...
    SET_USER_AGENT = ...
    ENABLE_STRICT_OBJECT_CREATION = ...
    ENABLE_STRICT_SYMBOLIC_REF_CREATION = ...
    SET_SSL_CIPHERS = ...
    GET_USER_AGENT = ...
    ENABLE_OFS_DELTA = ...
    ENABLE_FSYNC_GITDIR = ...
    GET_WINDOWS_SHAREMODE = ...
    SET_WINDOWS_SHAREMODE = ...
    ENABLE_STRICT_HASH_VERIFICATION = ...
    SET_ALLOCATOR = ...
    ENABLE_UNSAVED_INDEX_SAFETY = ...
    GET_PACK_MAX_OBJECTS = ...
    SET_PACK_MAX_OBJECTS = ...
    DISABLE_PACK_KEEP_FILE_CHECKS = ...
    GET_OWNER_VALIDATION = ...
    SET_OWNER_VALIDATION = ...
    GET_HOMEDIR = ...
    SET_HOMEDIR = ...
    GET_SERVER_CONNECT_TIMEOUT = ...
    SET_SERVER_CONNECT_TIMEOUT = ...
    ENABLE_HTTP_EXPECT_CONTINUE = ...
    GET_EXTENSIONS = ...
    SET_EXTENSIONS = ...
    ADD_SSL_X509_CERT = ...
    GET_USER_AGENT_PRODUCT = ...
    SET_USER_AGENT_PRODUCT = ...
    GET_SERVER_TIMEOUT = ...
    SET_SERVER_TIMEOUT = ...
    SET_ODB_PACKED_PRIORITY = ...
    SET_ODB_LOOSE_PRIORITY = ...

class ReferenceFilter(IntEnum):
    ALL = ...
    BRANCHES = ...
    TAGS = ...

class ReferenceType(IntFlag):
    INVALID = ...
    DIRECT = ...
    SYMBOLIC = ...
    ALL = ...
    OID = ...
    LISTALL = ...

class RepositoryInitFlag(IntFlag):
    BARE = ...
    NO_REINIT = ...
    NO_DOTGIT_DIR = ...
    MKDIR = ...
    MKPATH = ...
    EXTERNAL_TEMPLATE = ...
    RELATIVE_GITLINK = ...

class RepositoryInitMode(IntEnum):
    SHARED_UMASK = ...
    SHARED_GROUP = ...
    SHARED_ALL = ...

class RepositoryOpenFlag(IntFlag):
    DEFAULT = ...
    NO_SEARCH = ...
    CROSS_FS = ...
    BARE = ...
    NO_DOTGIT = ...
    FROM_ENV = ...

class RepositoryState(IntEnum):
    NONE = ...
    MERGE = ...
    REVERT = ...
    REVERT_SEQUENCE = ...
    CHERRYPICK = ...
    CHERRYPICK_SEQUENCE = ...
    BISECT = ...
    REBASE = ...
    REBASE_INTERACTIVE = ...
    REBASE_MERGE = ...
    APPLY_MAILBOX = ...
    APPLY_MAILBOX_OR_REBASE = ...

class ResetMode(IntEnum):
    SOFT = ...
    MIXED = ...
    HARD = ...

class RevSpecFlag(IntFlag):
    SINGLE = ...
    RANGE = ...
    MERGE_BASE = ...

class SortMode(IntFlag):
    NONE = ...
    TOPOLOGICAL = ...
    TIME = ...
    REVERSE = ...

class StashApplyProgress(IntEnum):
    NONE = ...
    LOADING_STASH = ...
    ANALYZE_INDEX = ...
    ANALYZE_MODIFIED = ...
    ANALYZE_UNTRACKED = ...
    CHECKOUT_UNTRACKED = ...
    CHECKOUT_MODIFIED = ...
    DONE = ...

class SubmoduleIgnore(IntEnum):
    UNSPECIFIED = ...
    NONE = ...
    UNTRACKED = ...
    DIRTY = ...
    ALL = ...

class SubmoduleStatus(IntFlag):
    IN_HEAD = ...
    IN_INDEX = ...
    IN_CONFIG = ...
    IN_WD = ...
    INDEX_ADDED = ...
    INDEX_DELETED = ...
    INDEX_MODIFIED = ...
    WD_UNINITIALIZED = ...
    WD_ADDED = ...
    WD_DELETED = ...
    WD_MODIFIED = ...
    WD_INDEX_MODIFIED = ...
    WD_WD_MODIFIED = ...
    WD_UNTRACKED = ...
